import {
  S3Client,
  PutBucketPolicyCommand,
  GetBucketPolicyCommand,
  GetPublicAccessBlockCommand,
  GetBucketEncryptionCommand,
  GetBucketVersioningCommand
} from '@aws-sdk/client-s3';

const region = process.env.AWS_REGION || 'us-east-1';
const client = new S3Client({ region });
const environment = process.env.ENVIRONMENT || 'dev';

interface SecurityStatus {
  bucketName: string;
  publicAccessBlocked: boolean;
  encryptionEnabled: boolean;
  versioningEnabled: boolean;
  bucketPolicyConfigured: boolean;
}

/**
 * Configure bucket policy for signed URL access
 * This policy allows access only through signed URLs generated by authorized Lambda functions
 */
async function configureBucketPolicy(bucketName: string, accountId: string): Promise<void> {
  console.log(`Configuring bucket policy for ${bucketName}...`);

  const policy = {
    Version: '2012-10-17',
    Statement: [
      {
        Sid: 'DenyInsecureTransport',
        Effect: 'Deny',
        Principal: '*',
        Action: 's3:*',
        Resource: [
          `arn:aws:s3:::${bucketName}`,
          `arn:aws:s3:::${bucketName}/*`
        ],
        Condition: {
          Bool: {
            'aws:SecureTransport': 'false'
          }
        }
      },
      {
        Sid: 'AllowSignedURLAccess',
        Effect: 'Allow',
        Principal: {
          AWS: `arn:aws:iam::${accountId}:root`
        },
        Action: [
          's3:GetObject',
          's3:PutObject'
        ],
        Resource: `arn:aws:s3:::${bucketName}/*`
      }
    ]
  };

  try {
    await client.send(new PutBucketPolicyCommand({
      Bucket: bucketName,
      Policy: JSON.stringify(policy)
    }));
    console.log(`  ✓ Bucket policy configured for signed URL access`);
  } catch (error: any) {
    console.error(`  ✗ Failed to configure bucket policy: ${error.message}`);
    throw error;
  }
}

/**
 * Verify security configurations for a bucket
 */
async function verifyBucketSecurity(bucketName: string): Promise<SecurityStatus> {
  console.log(`\nVerifying security for ${bucketName}...`);

  const status: SecurityStatus = {
    bucketName,
    publicAccessBlocked: false,
    encryptionEnabled: false,
    versioningEnabled: false,
    bucketPolicyConfigured: false
  };

  try {
    // Check public access block
    const publicAccessBlock = await client.send(
      new GetPublicAccessBlockCommand({ Bucket: bucketName })
    );
    status.publicAccessBlocked = 
      publicAccessBlock.PublicAccessBlockConfiguration?.BlockPublicAcls === true &&
      publicAccessBlock.PublicAccessBlockConfiguration?.IgnorePublicAcls === true &&
      publicAccessBlock.PublicAccessBlockConfiguration?.BlockPublicPolicy === true &&
      publicAccessBlock.PublicAccessBlockConfiguration?.RestrictPublicBuckets === true;
    
    console.log(`  ${status.publicAccessBlocked ? '✓' : '✗'} Public access blocked`);
  } catch (error: any) {
    console.log(`  ✗ Public access block not configured: ${error.message}`);
  }

  try {
    // Check encryption
    const encryption = await client.send(
      new GetBucketEncryptionCommand({ Bucket: bucketName })
    );
    status.encryptionEnabled = 
      encryption.ServerSideEncryptionConfiguration?.Rules?.[0]
        ?.ApplyServerSideEncryptionByDefault?.SSEAlgorithm === 'AES256';
    
    console.log(`  ${status.encryptionEnabled ? '✓' : '✗'} AES-256 encryption enabled`);
  } catch (error: any) {
    console.log(`  ✗ Encryption not configured: ${error.message}`);
  }

  try {
    // Check versioning
    const versioning = await client.send(
      new GetBucketVersioningCommand({ Bucket: bucketName })
    );
    status.versioningEnabled = versioning.Status === 'Enabled';
    
    console.log(`  ${status.versioningEnabled ? '✓' : '✗'} Versioning enabled`);
  } catch (error: any) {
    console.log(`  ✗ Versioning not configured: ${error.message}`);
  }

  try {
    // Check bucket policy
    await client.send(
      new GetBucketPolicyCommand({ Bucket: bucketName })
    );
    status.bucketPolicyConfigured = true;
    console.log(`  ✓ Bucket policy configured`);
  } catch (error: any) {
    if (error.name === 'NoSuchBucketPolicy') {
      console.log(`  ✗ No bucket policy configured`);
    } else {
      console.log(`  ✗ Failed to check bucket policy: ${error.message}`);
    }
  }

  return status;
}

/**
 * Configure security for QR codes bucket
 */
async function configureQRCodesBucketSecurity(accountId: string): Promise<void> {
  const bucketName = `gp-qr-codes-${environment}`;
  console.log(`\n=== Configuring QR Codes Bucket Security ===`);
  
  await configureBucketPolicy(bucketName, accountId);
  await verifyBucketSecurity(bucketName);
}

/**
 * Verify security for frontend bucket
 */
async function verifyFrontendBucketSecurity(): Promise<void> {
  const bucketName = `gp-frontend-${environment}`;
  console.log(`\n=== Verifying Frontend Bucket Security ===`);
  
  await verifyBucketSecurity(bucketName);
}

async function main() {
  try {
    console.log(`Starting S3 security configuration for environment: ${environment}\n`);

    // Get AWS account ID from environment or prompt
    const accountId = process.env.AWS_ACCOUNT_ID;
    if (!accountId) {
      console.error('Error: AWS_ACCOUNT_ID environment variable is required');
      console.log('Set it with: export AWS_ACCOUNT_ID=your-account-id');
      process.exit(1);
    }

    // Configure QR codes bucket security
    await configureQRCodesBucketSecurity(accountId);

    // Verify frontend bucket security (no policy needed, accessed via CloudFront)
    await verifyFrontendBucketSecurity();

    console.log('\n✓ S3 security configuration completed successfully');
    console.log('\nSecurity Summary:');
    console.log('- QR codes bucket: Private access, encryption, versioning, signed URL policy');
    console.log('- Frontend bucket: CloudFront access, encryption, static website hosting');
  } catch (error) {
    console.error('\nError configuring S3 security:', error);
    process.exit(1);
  }
}

// Run if executed directly
if (require.main === module) {
  main();
}

export {
  configureBucketPolicy,
  verifyBucketSecurity,
  configureQRCodesBucketSecurity,
  verifyFrontendBucketSecurity
};
